import { DarkTheme } from "@/constants/ui";
import { StyleSheet } from "react-native";

export const getSettingsStyles = (colors: any) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.4)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      width: "85%",
      borderRadius: 20,
      padding: 24,
      borderWidth: 0.5,
      borderColor: colors.PRIMARY_BORDER_DARK,
      backgroundColor: colors.SECONDARY_BACKGROUND,
      elevation: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 10,
    },
    modalPremiumContainer: {
      backgroundColor: colors.SECONDARY_BACKGROUND,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.PRIMARY_BORDER_DARK,
      padding: 20,
      width: 340,
      maxWidth: "95%",
      alignItems: "center",
      gap: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 10,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
      width: "100%",
      marginBottom: 4,
    },
    iconContainer: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.SECONDARY_BACKGROUND,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 2,
    },
    standardDivider: {
      height: 0.6,
      backgroundColor: colors.PRIMARY_BORDER_DARK,
      width: "100%",
      opacity: 0.8,
      marginVertical: 4,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 24,
    },
    title: {
      fontSize: 22,
      fontWeight: "bold",
      color: colors.PRIMARY_TEXT,
    },
    section: {
      marginBottom: 24,
    },
    divider: {
      height: 0.3,
      width: "100%",
      marginVertical: 24,
      backgroundColor: colors.PRIMARY_BORDER_DARK,
      opacity: 0.1,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: "600",
      marginBottom: 10,
      color: colors.PLACEHOLDER,
      marginLeft: 4,
      opacity: 0.9,
    },
    optionsContainer: {
      flexDirection: "row",
      gap: 12,
    },
    optionButton: {
      flex: 1,
      flexDirection: "row",
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 12,
      borderWidth: 0.2,
      borderColor: colors.PRIMARY_BORDER_DARK,
      backgroundColor: colors.TAB_BAR,
      alignItems: "center",
      justifyContent: "center",
    },
    optionText: {
      fontWeight: "600",
      fontSize: 14,
    },
    aboutContainer: {
      borderRadius: 16,
      overflow: "hidden",
      borderWidth: 0.2,
      borderColor: colors.PRIMARY_BORDER_DARK,
    },
    aboutRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderBottomWidth: 0.2,
      borderColor: colors.PRIMARY_BORDER_DARK,
      backgroundColor: colors.SECONDARY_BACKGROUND,
    },
    aboutLabel: {
      fontSize: 15,
      fontWeight: "500",
      color: colors.PRIMARY_TEXT,
    },
    aboutValue: {
      fontSize: 15,
      color: colors.PLACEHOLDER,
    },
    headerText: {
      fontSize: 14,
      fontWeight: "bold",
      textAlign: "center",
      opacity: 0.9,
      color: colors.PRIMARY_TEXT,
    },
  });

// For backward compatibility
export const styles = getSettingsStyles(DarkTheme);
