import { StyleSheet } from "react-native";

export const getStyles = (colors: any, isDark: boolean) =>
  StyleSheet.create({
    container: {
      borderRadius: 24,
      borderWidth: 1,
      padding: 24,
      width: 340,
      maxWidth: "90%",
      gap: 10,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDark ? 0.3 : 0.2, // Increased opacity for light mode definition
      shadowRadius: isDark ? 20 : 15, // Tighter shadow for light mode
      elevation: 10,
      backgroundColor: colors.SECONDARY_BACKGROUND,
      borderColor: isDark ? colors.PRIMARY_BORDER_DARK : colors.PRIMARY_BORDER, // More distinct border in light mode
    },
    headerRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 12,
      justifyContent: "center",
      width: "100%",
      marginBottom: 4,
    },
    headerIconContainer: {
      backgroundColor: colors.SECONDARY_BACKGROUND,
      shadowColor: colors.PRIMARY_ACTIVE_BUTTON,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 2,
      width: 42,
      height: 42,
      borderRadius: 21,
      justifyContent: "center",
      alignItems: "center",
      flexShrink: 0,
    },
    headerText: {
      fontSize: 14,
      fontWeight: "bold",
      color: colors.PRIMARY_TEXT,
      textAlign: "left",
    },
    divider: {
      height: 1,
      width: "100%",
      backgroundColor: isDark ? "rgba(255,255,255,0.1)" : "rgba(0,0,0,0.05)",
      marginBottom: 4,
    },
    tableContainer: {
      width: "100%",
      backgroundColor: isDark ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.03)",
      borderRadius: 16,
      padding: 2,
      overflow: "hidden",
    },
    tableRow: {
      flexDirection: "row",
      paddingVertical: 14,
      paddingHorizontal: 12,
      alignItems: "center",
    },
    tableRowBorder: {
      borderTopWidth: 1,
      borderTopColor: isDark ? "rgba(255,255,255,0.15)" : "rgba(0,0,0,0.15)",
    },
    tableLabelColumn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    tableLabelText: {
      fontSize: 12,
      color: colors.SECTION_TEXT,
      fontWeight: "500",
    },
    tableValueColumn: {
      flex: 1.5,
      alignItems: "flex-end",
    },
    tableValueText: {
      fontSize: 12,
      color: colors.PRIMARY_TEXT,
      fontWeight: "600",
    },
    miniCalendarWrapper: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      alignItems: "center",
      gap: 12,
      width: "100%",
    },
    miniCalendarContainer: {
      width: 30,
      height: 34,
      borderRadius: 7,
      borderWidth: 1,
      overflow: "hidden",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1,
      elevation: 1,
      backgroundColor: colors.SECONDARY_BACKGROUND,
      borderColor: isDark ? "rgba(255,255,255,0.12)" : "rgba(0,0,0,0.08)",
    },
    miniCalendarHeader: {
      width: "100%",
      height: 11,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.PRIMARY_ACTIVE_BUTTON,
    },
    iterativeContainer: {
      width: "100%",
      gap: 8,
    },
    miniCalendarHeaderText: {
      fontSize: 7,
      color: "#ffffff",
      fontWeight: "700",
      lineHeight: 10,
    },
    miniCalendarBody: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    miniCalendarBodyText: {
      fontSize: 11.5,
      fontWeight: "600",
    },
  });
