import { StyleSheet } from "react-native";

export const getAddStyles = (colors: any, isDark: boolean) =>
  StyleSheet.create({
    container: {
      borderRadius: 24,
      borderWidth: 1,
      padding: 20,
      width: 340,
      maxWidth: "95%",
      gap: 10,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDark ? 0.3 : 0.2,
      shadowRadius: isDark ? 20 : 15,
      elevation: 10,
      backgroundColor: colors.SECONDARY_BACKGROUND,
      borderColor: isDark ? colors.PRIMARY_BORDER_DARK : colors.PRIMARY_BORDER,
    },
    headerRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 12,
      justifyContent: "center",
      width: "100%",
      marginBottom: 4,
    },
    headerIconContainer: {
      backgroundColor: colors.SECONDARY_BACKGROUND,
      shadowColor: colors.PRIMARY_ACTIVE_BUTTON,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 2,
      width: 42,
      height: 42,
      borderRadius: 21,
      flexShrink: 0,
      alignItems: "center",
      justifyContent: "center",
    },
    tableContainer: {
      width: "100%",
      backgroundColor: isDark ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.03)",
      borderRadius: 16,
      padding: 4,
      overflow: "hidden",
    },
    tableRow: {
      flexDirection: "row",
      paddingVertical: 12,
      paddingHorizontal: 12,
      alignItems: "center",
    },
    tableRowBorder: {
      borderTopWidth: 1,
      borderTopColor: isDark ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.05)",
    },
    tableLabelColumn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    tableLabelText: {
      fontSize: 12,
      color: colors.SECTION_TEXT,
      fontWeight: "500",
    },
    tableValueColumn: {
      flex: 2,
      alignItems: "flex-end",
    },
    tableValueText: {
      fontSize: 13,
      color: colors.PRIMARY_TEXT,
      fontWeight: "600",
      width: "100%",
      textAlign: "right",
    },
    headerText: {
      fontSize: 14,
      fontWeight: "bold",
      textAlign: "center",
      opacity: 0.9,
      color: colors.PRIMARY_TEXT,
    },
    inputError: {
      borderColor: colors.ERROR_INPUT_TEXT,
      borderWidth: 1.5,
    },
    visualizerContainer: {
      height: 80,
      width: "100%",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 20,
    },
    barsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      height: 60,
    },
    visualizerBar: {
      width: 3,
      height: "100%",
      backgroundColor: "#ea4335",
      borderRadius: 1.5,
    },
    analyzingLoader: {
      height: 60,
      justifyContent: "center",
      alignItems: "center",
    },
    micCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: isDark
        ? "rgba(255, 255, 255, 0.05)"
        : "rgba(0, 0, 0, 0.03)",
      borderWidth: 2,
      borderColor: isDark ? "rgba(255, 255, 255, 0.1)" : "rgba(0, 0, 0, 0.1)",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
    },
    voiceModalStatusText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.PRIMARY_TEXT,
      letterSpacing: 1.2,
      textTransform: "uppercase",
      opacity: 0.8,
    },
    timerContainer: {
      width: "100%",
      marginTop: 10,
      alignItems: "center",
    },
    progressBarBackground: {
      width: "100%",
      height: 4,
      backgroundColor: isDark
        ? "rgba(255, 255, 255, 0.1)"
        : "rgba(0, 0, 0, 0.05)",
      borderRadius: 2,
      overflow: "hidden",
      marginBottom: 8,
    },
    progressBarFill: {
      height: "100%",
      backgroundColor: "#ea4335",
      borderRadius: 2,
    },
    timerText: {
      fontSize: 12,
      color: colors.PLACEHOLDER,
      fontWeight: "500",
    },
    stopRecordingButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(234, 67, 53, 0.1)",
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 20,
      marginTop: 25,
      borderWidth: 1,
      borderColor: "rgba(234, 67, 53, 0.3)",
      gap: 10,
    },
    stopIcon: {
      width: 12,
      height: 12,
      backgroundColor: "#ea4335",
      borderRadius: 2,
    },
    stopButtonText: {
      color: "#ea4335",
      fontWeight: "bold",
      fontSize: 14,
    },
    categoryContainer: {
      width: "100%",
      marginTop: 12,
      paddingHorizontal: 4,
    },
    categoryList: {
      flexDirection: "row",
      gap: 8,
      paddingRight: 12,
    },
    categoryItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      paddingHorizontal: 10,
      borderRadius: 15,
      borderWidth: 0.2,
      gap: 6,
    },
    divider: {
      height: 0.6,
      backgroundColor: colors.PRIMARY_BORDER_DARK,
      width: "100%",
      opacity: 0.8,
      marginVertical: 4,
    },
    buttonsContainer: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 12,
      width: "100%",
    },
    voiceModalContainer: {
      backgroundColor: colors.SECONDARY_BACKGROUND,
      borderRadius: 15,
      borderWidth: 0.5,
      borderColor: colors.PRIMARY_BORDER_DARK,
      padding: 20,
      minWidth: 280,
      alignItems: "center",
      gap: 12,
      minHeight: 280,
      paddingVertical: 30,
    },
  });
