import { StyleSheet } from "react-native";

export const getAddStyles = (colors: any, isDark: boolean) => StyleSheet.create({
    container: {
        borderRadius: 24,
        borderWidth: 1,
        padding: 24,
        minWidth: 340,
        gap: 12,
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: isDark ? 0.3 : 0.2,
        shadowRadius: isDark ? 20 : 15,
        elevation: 10,
        backgroundColor: colors.SECONDARY_BACKGROUND,
        borderColor: isDark ? colors.PRIMARY_BORDER_DARK : colors.PRIMARY_BORDER,
    },
    presetsRow: {
        flexDirection: 'row',
        gap: 8,
        marginVertical: 4,
        width: '100%'
    },
    presetButton: {
        flex: 1,
        paddingVertical: 10,
        paddingHorizontal: 4,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 0.5,
    },
    presetText: {
        fontSize: 10,
        fontWeight: '700',
        lineHeight: 14,
        textAlign: 'center'
    },
    tableContainer: {
        width: "100%",
        backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.03)',
        borderRadius: 16,
        padding: 4,
        overflow: 'hidden',
    },
    tableRow: {
        flexDirection: 'row',
        paddingVertical: 14,
        paddingHorizontal: 12,
        alignItems: 'center',
    },
    tableRowBorder: {
        borderTopWidth: 1,
        borderTopColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)',
    },
    tableLabelColumn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    tableLabelText: {
        fontSize: 12,
        color: colors.SECTION_TEXT,
        fontWeight: "500",
    },
    tableValueColumn: {
        flex: 2,
        alignItems: 'flex-end',
    },
    tableValueText: {
        fontSize: 13,
        color: colors.PRIMARY_TEXT,
        fontWeight: "600",
        width: '100%',
        textAlign: 'right',
    },
    headerText: {
        fontSize: 18,
        fontWeight: "bold",
        textAlign: 'center',
        opacity: 0.8,
        color: colors.PRIMARY_TEXT,
    },
    inputWrapper: {
        backgroundColor: isDark ? "rgba(255, 255, 255, 0.05)" : "rgba(0, 0, 0, 0.03)",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: isDark ? "rgba(255, 255, 255, 0.1)" : "rgba(0, 0, 0, 0.1)",
        paddingHorizontal: 16,
        paddingVertical: 12,
        minHeight: 60,
        width: "100%",
        marginBottom: 16,
    },
    inputFocused: {
        backgroundColor: isDark ? "rgba(255, 255, 255, 0.05)" : "rgba(0, 0, 0, 0.02)",
        borderColor: colors.CHECKBOX_SUCCESS,
        borderWidth: 1.5,
        shadowColor: colors.CHECKBOX_SUCCESS,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 5,
    },
    inputError: {
        borderColor: colors.ERROR_INPUT_TEXT,
        borderWidth: 1.5,
    },
    textInput: {
        color: colors.PRIMARY_TEXT,
        fontSize: 16,
        minHeight: 40,
        textAlign: 'left',
        textAlignVertical: 'center',
        paddingHorizontal: 8,
        lineHeight: 16,
    },
    addReminderButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: colors.TAB_BAR,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.PRIMARY_BORDER_DARK,
        gap: 10,
        flex: 1,
    },
    actionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 10,
    },
    voiceButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.03)',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 12,
        gap: 8,
        flex: 1,
        justifyContent: 'center',
        borderWidth: 0.2,
        borderColor: colors.SECTION_TEXT
    },
    voiceButtonActive: {
        backgroundColor: "rgba(234, 67, 53, 0.2)",
        borderColor: "#ea4335",
    },
    addReminderText: {
        color: colors.PLACEHOLDER,
        fontSize: 14,
        fontWeight: "500",
    },
    reminderChip: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: "#39b2e6ff",
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 35,
        position: 'relative',
    },
    chipContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    chipText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "600",
        textAlign: 'center',
    },
    clearButton: {
        position: 'absolute',
        right: 5,
        padding: 4,
    },
    iosPickerContainer: {
        backgroundColor: colors.SECONDARY_BACKGROUND,
        borderRadius: 20,
        paddingBottom: 20,
        width: '100%',
        overflow: 'hidden',
    },
    iosHeader: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)',
        backgroundColor: isDark ? 'rgba(0,0,0,0.2)' : 'rgba(0,0,0,0.02)',
    },
    iosTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.PRIMARY_TEXT,
    },
    iconButton: {
        padding: 4,
    },
    pickerWrapper: {
        marginTop: 10,
        width: '100%',
        height: 150,
        justifyContent: 'center',
        overflow: 'hidden',
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: isDark ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.05)',
    },
    voiceOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: isDark ? "rgba(21, 22, 22, 0.8)" : "rgba(255, 255, 255, 0.9)",
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 20,
    },
    waveContainer: {
        width: 80,
        height: 80,
        justifyContent: 'center',
        alignItems: 'center',
    },
    wave: {
        position: 'absolute',
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#ea4335",
    },
    visualizerContainer: {
        height: 80,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    barsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        height: 60,
    },
    visualizerBar: {
        width: 3,
        height: '100%',
        backgroundColor: "#ea4335",
        borderRadius: 1.5,
    },
    analyzingLoader: {
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
    },
    micCircle: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: isDark ? "rgba(255, 255, 255, 0.05)" : "rgba(0, 0, 0, 0.03)",
        borderWidth: 2,
        borderColor: isDark ? "rgba(255, 255, 255, 0.1)" : "rgba(0, 0, 0, 0.1)",
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    voiceModalStatusText: {
        fontSize: 13,
        fontWeight: "600",
        color: colors.PRIMARY_TEXT,
        letterSpacing: 1.2,
        textTransform: 'uppercase',
        opacity: 0.8,
    },
    timerContainer: {
        width: '100%',
        marginTop: 10,
        alignItems: 'center',
    },
    progressBarBackground: {
        width: '100%',
        height: 4,
        backgroundColor: isDark ? "rgba(255, 255, 255, 0.1)" : "rgba(0, 0, 0, 0.05)",
        borderRadius: 2,
        overflow: 'hidden',
        marginBottom: 8,
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: "#ea4335",
        borderRadius: 2,
    },
    timerText: {
        fontSize: 12,
        color: colors.PLACEHOLDER,
        fontWeight: "500",
    },
    stopRecordingButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: "rgba(234, 67, 53, 0.1)",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 20,
        marginTop: 25,
        borderWidth: 1,
        borderColor: "rgba(234, 67, 53, 0.3)",
        gap: 10,
    },
    stopIcon: {
        width: 12,
        height: 12,
        backgroundColor: "#ea4335",
        borderRadius: 2,
    },
    stopButtonText: {
        color: "#ea4335",
        fontWeight: "bold",
        fontSize: 14,
    }
});
