import { COLORS } from "@/constants/ui";
import { StyleSheet } from "react-native";

export const localStyles = StyleSheet.create({
    inputWrapper: {
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.1)",
        paddingHorizontal: 16,
        paddingVertical: 12,
        minHeight: 60,
        width: "100%",
        marginBottom: 16,
    },
    inputFocused: {
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        borderColor: "rgba(255, 255, 255, 0.3)",
        borderWidth: 1,
        shadowColor: "rgba(255, 255, 255, 0.5)",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 5,
    },
    inputError: {
        borderColor: COLORS.ERROR_INPUT_TEXT,
    },
    textInput: {
        color: COLORS.PRIMARY_TEXT,
        fontSize: 16,
        minHeight: 40,
        textAlign: 'left',
        textAlignVertical: 'center',
        paddingHorizontal: 8,
        lineHeight: 16,
    },
    addReminderButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: "#151616ff",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#3a3f47",
        gap: 10,
        flex: 1,
    },
    actionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 10,
    },
    voiceButton: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: "#151616ff",
        borderWidth: 1,
        borderColor: "#3a3f47",
        justifyContent: 'center',
        alignItems: 'center',
    },
    voiceButtonActive: {
        backgroundColor: "rgba(234, 67, 53, 0.2)",
        borderColor: "#ea4335",
    },
    addReminderText: {
        color: "#888",
        fontSize: 14,
        fontWeight: "500",
    },
    reminderChip: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: "#39b2e6ff",
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 35,
        position: 'relative',
    },
    chipContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    chipText: {
        color: "#000",
        fontSize: 14,
        fontWeight: "600",
        textAlign: 'center',
    },
    clearButton: {
        position: 'absolute',
        right: 5,
        padding: 4,
    },
    iosPickerContainer: {
        backgroundColor: COLORS.SECONDARY_BACKGROUND,
        borderRadius: 20,
        paddingBottom: 20,
        width: '100%',
        overflow: 'hidden',
    },
    iosHeader: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.05)',
        backgroundColor: 'rgba(0,0,0,0.2)',
    },
    iosTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.PRIMARY_TEXT,
    },
    iconButton: {
        padding: 4,
    },
    pickerWrapper: {
        marginTop: 10,
        width: '100%',
        height: 150,
        justifyContent: 'center',
        overflow: 'hidden',
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    voiceOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(21, 22, 22, 0.8)",
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 20,
    },
    waveContainer: {
        width: 80,
        height: 80,
        justifyContent: 'center',
        alignItems: 'center',
    },
    wave: {
        position: 'absolute',
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#ea4335",
    },
    visualizerContainer: {
        height: 80,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    barsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        height: 60,
    },
    visualizerBar: {
        width: 3,
        height: '100%',
        backgroundColor: "#ea4335",
        borderRadius: 1.5,
    },
    analyzingLoader: {
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
    },
    micCircle: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        borderWidth: 2,
        borderColor: "rgba(255, 255, 255, 0.1)",
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    voiceModalStatusText: {
        fontSize: 14,
        fontWeight: "600",
        color: COLORS.PRIMARY_TEXT,
        letterSpacing: 1.5,
        textTransform: 'uppercase',
    },
    timerContainer: {
        width: '100%',
        marginTop: 10,
        alignItems: 'center',
    },
    progressBarBackground: {
        width: '100%',
        height: 4,
        backgroundColor: "rgba(255, 255, 255, 0.1)",
        borderRadius: 2,
        overflow: 'hidden',
        marginBottom: 8,
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: "#ea4335",
        borderRadius: 2,
    },
    timerText: {
        fontSize: 12,
        color: COLORS.PLACEHOLDER,
        fontWeight: "500",
    },
    stopRecordingButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: "rgba(234, 67, 53, 0.1)",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 20,
        marginTop: 25,
        borderWidth: 1,
        borderColor: "rgba(234, 67, 53, 0.3)",
        gap: 10,
    },
    stopIcon: {
        width: 12,
        height: 12,
        backgroundColor: "#ea4335",
        borderRadius: 2,
    },
    stopButtonText: {
        color: "#ea4335",
        fontWeight: "bold",
        fontSize: 14,
    }
});
