import { StyleSheet } from "react-native";

export const getEditStyles = (colors: any, isDark: boolean) => StyleSheet.create({
    container: {
        borderRadius: 24,
        borderWidth: 1,
        padding: 24,
        minWidth: 340,
        gap: 12,
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: isDark ? 0.3 : 0.2,
        shadowRadius: isDark ? 20 : 15,
        elevation: 10,
        backgroundColor: colors.SECONDARY_BACKGROUND,
        borderColor: isDark ? colors.PRIMARY_BORDER_DARK : colors.PRIMARY_BORDER,
    },
    presetsRow: {
        flexDirection: 'row',
        gap: 8,
        marginVertical: 4,
        width: '100%'
    },
    presetButton: {
        flex: 1,
        paddingVertical: 10,
        paddingHorizontal: 4,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 0.5,
    },
    presetText: {
        fontSize: 10,
        fontWeight: '700',
        lineHeight: 14,
        textAlign: 'center'
    },
    tableContainer: {
        width: "100%",
        backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.03)',
        borderRadius: 16,
        padding: 4,
        overflow: 'hidden',
    },
    tableRow: {
        flexDirection: 'row',
        paddingVertical: 14,
        paddingHorizontal: 12,
        alignItems: 'center',
    },
    tableRowBorder: {
        borderTopWidth: 1,
        borderTopColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)',
    },
    tableLabelColumn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    tableLabelText: {
        fontSize: 12,
        color: colors.SECTION_TEXT,
        fontWeight: "500",
    },
    tableValueColumn: {
        flex: 2,
        alignItems: 'flex-end',
    },
    tableValueText: {
        fontSize: 13,
        color: colors.PRIMARY_TEXT,
        fontWeight: "600",
        width: '100%',
        textAlign: 'right',
    },
    headerText: {
        fontSize: 18,
        fontWeight: "bold",
        textAlign: 'center',
        opacity: 0.8,
        color: colors.PRIMARY_TEXT,
    },
    inputWrapper: {
        backgroundColor: isDark ? "rgba(255, 255, 255, 0.05)" : "rgba(0, 0, 0, 0.03)",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: isDark ? "rgba(255, 255, 255, 0.1)" : "rgba(0, 0, 0, 0.1)",
        paddingHorizontal: 16,
        paddingVertical: 12,
        minHeight: 60,
        width: "100%",
    },
    inputFocused: {
        backgroundColor: isDark ? "rgba(255, 255, 255, 0.05)" : "rgba(0, 0, 0, 0.02)",
        borderColor: colors.CHECKBOX_SUCCESS,
        borderWidth: 1.5,
        shadowColor: colors.CHECKBOX_SUCCESS,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 5,
    },
    inputError: {
        borderColor: colors.ERROR_INPUT_TEXT,
        borderWidth: 1.5,
    },
    textInput: {
        color: colors.PRIMARY_TEXT,
        fontSize: 16,
        minHeight: 40,
        textAlign: 'left',
        textAlignVertical: 'center',
        paddingHorizontal: 8,
        lineHeight: 16,
    },
    sectionLabel: {
        fontSize: 12,
        color: colors.PLACEHOLDER,
        marginBottom: 8,
        marginLeft: 4,
        fontWeight: "600",
        textTransform: "uppercase",
        letterSpacing: 0.5
    },
    pickerRow: {
        flexDirection: "row",
        gap: 10,
        alignItems: "center"
    },
    pickerButton: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.TAB_BAR,
        paddingVertical: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.PRIMARY_BORDER_DARK,
        gap: 8,
    },
    pickerButtonActive: {
        borderColor: "#5BC0EB",
        backgroundColor: "rgba(91, 192, 235, 0.05)"
    },
    pickerText: {
        color: colors.PLACEHOLDER,
        fontSize: 14,
        fontWeight: "500"
    },
    addReminderButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: colors.TAB_BAR,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.PRIMARY_BORDER_DARK,
        gap: 10,
    },
    addReminderText: {
        color: colors.PLACEHOLDER,
        fontSize: 14,
        fontWeight: "500",
    },
    reminderChip: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: "#39b2e6ff",
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 35,
        position: 'relative',
    },
    chipContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    chipText: {
        color: "#fff",
        fontSize: 15,
        fontWeight: "600",
        textAlign: 'center',
    },
    clearButton: {
        position: 'absolute',
        right: 5,
        padding: 4,
    },
    iosPickerContainer: {
        backgroundColor: colors.SECONDARY_BACKGROUND,
        borderRadius: 20,
        paddingBottom: 20,
        width: '100%',
        overflow: 'hidden',
    },
    iosHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)',
        backgroundColor: isDark ? 'rgba(0,0,0,0.2)' : 'rgba(0,0,0,0.02)',
    },
    iosTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.PRIMARY_TEXT,
    },
    iconButton: {
        padding: 4,
    },
    pickerWrapper: {
        marginTop: 10,
        width: '100%',
        height: 150,
        justifyContent: 'center',
        overflow: 'hidden',
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: isDark ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.05)',
    }
});
