import { StyleSheet } from "react-native"

export const getStyles = (colors: any, isDark: boolean) => StyleSheet.create({
    container: {
        borderRadius: 28,
        borderWidth: 1,
        padding: 0, // Control padding internally
        width: 360,
        maxWidth: "95%",
        overflow: 'hidden',
        backgroundColor: colors.SECONDARY_BACKGROUND,
        borderColor: isDark ? colors.PRIMARY_BORDER_DARK : colors.PRIMARY_BORDER,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: isDark ? 0.4 : 0.15,
        shadowRadius: 24,
        elevation: 12,
    },
    headerWrapper: {
        padding: 20,
        paddingBottom: 10,
        alignItems: 'center',
    },
    headerText: {
        fontSize: 18,
        fontWeight: "bold",
        color: colors.PRIMARY_TEXT,
        marginBottom: 10,
    },
    recipientCard: {
        flexDirection: "row",
        alignItems: "center",
        padding: 12,
        backgroundColor: isDark ? 'rgba(212, 136, 15, 0.1)' : 'rgba(212, 136, 15, 0.05)',
        borderRadius: 16,
        width: '90%',
        alignSelf: 'center',
        marginBottom: 15,
    },
    recipientAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    recipientInfo: {
        marginLeft: 12,
    },
    recipientLabel: {
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    recipientName: {
        fontSize: 14,
        fontWeight: "600",
        color: colors.PRIMARY_TEXT,
    },
    tabsRow: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        gap: 8,
        marginBottom: 15,
    },
    tabButton: {
        flex: 1,
        height: 40,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        gap: 6,
        borderWidth: 1,
        borderColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
        backgroundColor: isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.02)',
    },
    activeTab: {
        backgroundColor: colors.PRIMARY_ACTIVE_BUTTON,
        borderColor: colors.PRIMARY_ACTIVE_BUTTON,
    },
    tabText: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.SECTION_TEXT,
    },
    activeTabText: {
        color: '#FFFFFF',
    },
    contentArea: {
        paddingHorizontal: 20,
        height: 380, // Fixed height to prevent modal jumping
    },
    greetingsScroll: {
        flex: 1,
    },
    greetingCard: {
        flexDirection: "row",
        alignItems: "center",
        padding: 14,
        borderRadius: 14,
        borderWidth: 1,
        marginBottom: 10,
        gap: 12,
        backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : '#FFFFFF',
        borderColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.08)',
    },
    selectedGreeting: {
        borderColor: colors.PRIMARY_ACTIVE_BUTTON,
        backgroundColor: isDark ? 'rgba(35, 78, 148, 0.15)' : 'rgba(35, 78, 148, 0.05)',
    },
    greetingText: {
        flex: 1,
        fontSize: 13,
        lineHeight: 18,
        color: colors.PRIMARY_TEXT,
    },
    customContainer: {
        marginTop: 5,
        borderRadius: 14,
        borderWidth: 1,
        paddingHorizontal: 12,
        paddingVertical: 10,
        backgroundColor: isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.02)',
        borderColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)',
        flexDirection: 'row',
        alignItems: 'flex-end',
    },
    customInput: {
        flex: 1,
        fontSize: 13,
        minHeight: 60,
        textAlignVertical: "top",
        color: colors.PRIMARY_TEXT,
    },
    cardPreviewContainer: {
        flex: 1,
        alignItems: 'center',
        gap: 15,
    },
    cardPreviewLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.PRIMARY_ACTIVE_BUTTON,
    },
    handwrittenContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 20,
        paddingBottom: 40,
    },
    drawHeroButton: {
        width: '100%',
        height: 120,
        borderRadius: 20,
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: colors.PRIMARY_ACTIVE_BUTTON,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: isDark ? 'rgba(35, 78, 148, 0.1)' : 'rgba(35, 78, 148, 0.05)',
        gap: 10,
    },
    drawHeroText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.PRIMARY_ACTIVE_BUTTON,
    },
    footer: {
        padding: 20,
        paddingTop: 10,
        gap: 10,
    },
    sendActionBtn: {
        width: '100%',
        backgroundColor: '#D4880F',
        height: 48,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        gap: 8,
    },
    sendActionText: {
        color: '#FFFFFF',
        fontWeight: 'bold',
        fontSize: 15,
    },
    secondaryBtn: {
        width: '100%',
        height: 44,
        justifyContent: 'center',
        alignItems: 'center',
    },
    secondaryBtnText: {
        color: colors.SECTION_TEXT,
        fontSize: 14,
        fontWeight: '500',
    },
    backgroundSelector: {
        width: '100%',
        maxHeight: 100,
        marginBottom: 10,
    },
    bgThumbnail: {
        width: 60,
        height: 75,
        borderRadius: 8,
        marginRight: 10,
        borderWidth: 2,
        borderColor: 'transparent',
        overflow: 'hidden',
    },
    activeBgThumbnail: {
        borderColor: colors.PRIMARY_ACTIVE_BUTTON,
    },
    bgThumbnailImage: {
        width: '100%',
        height: '100%',
    }
})
