import { StyleSheet } from "react-native"

export const getStyles = (colors: any, isDark: boolean) => StyleSheet.create({
    container: {
        width: 340,
        maxWidth: "90%",
        alignItems: 'center',
        padding: 24,
        borderRadius: 24,
        borderWidth: 1,
        gap: 12, // Added to match other modals
        backgroundColor: colors.SECONDARY_BACKGROUND,
        borderColor: isDark ? colors.PRIMARY_BORDER_DARK : colors.PRIMARY_BORDER,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: isDark ? 0.3 : 0.2,
        shadowRadius: 20,
        elevation: 10,
    },
    headerText: {
        fontSize: 18,
        fontWeight: "600",
        color: colors.PRIMARY_TEXT,
        textAlign: "center",
    },
    recipientCard: {
        flexDirection: "row",
        alignItems: "center",
        padding: 12,
        backgroundColor: isDark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.03)',
        borderRadius: 16,
        width: '100%',
    },
    recipientAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    recipientInfo: {
        marginLeft: 12,
    },
    recipientLabel: {
        fontSize: 11,
        fontWeight: '500',
    },
    recipientName: {
        fontSize: 15,
        fontWeight: "600",
        color: colors.PRIMARY_TEXT,
    },
    tabsRow: {
        flexDirection: 'row',
        width: '100%',
        gap: 6,
        marginBottom: 12,
    },
    tabButton: {
        flex: 1,
        height: 40,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        gap: 6,
        borderWidth: 0.2,
        borderColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
        backgroundColor: isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.02)',
    },
    activeTab: {
        backgroundColor: colors.PRIMARY_ACTIVE_BUTTON,
        borderColor: colors.PRIMARY_ACTIVE_BUTTON,
    },
    tabText: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.SECTION_TEXT,
    },
    activeTabText: {
        color: '#FFFFFF',
    },
    contentArea: {
        width: '100%',
    },
    greetingsScroll: {
        height: 240,
        width: '100%',
    },
    greetingsContent: {
        paddingBottom: 40,
        flexGrow: 1,
    },
    greetingCard: {
        flexDirection: "row",
        alignItems: "center",
        padding: 16,
        borderRadius: 16,
        marginTop: 10,
        width: '100%',
        backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.02)',
        borderWidth: 1,
        borderColor: 'transparent',
    },
    selectedGreeting: {
        borderColor: colors.PRIMARY_ACTIVE_BUTTON,
        backgroundColor: isDark ? 'rgba(35, 78, 148, 0.12)' : 'rgba(35, 78, 148, 0.05)',
    },
    greetingText: {
        flex: 1,
        fontSize: 14,
        lineHeight: 20,
        color: colors.PRIMARY_TEXT,
        fontWeight: '500',
    },
    cardPreviewContainer: {
        width: '100%',
        alignItems: 'center',
        paddingVertical: 0,
    },
    handwrittenContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 20,
        paddingBottom: 40,
    },
    drawHeroButton: {
        width: '100%',
        height: 120,
        borderRadius: 20,
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: colors.PRIMARY_ACTIVE_BUTTON,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: isDark ? 'rgba(35, 78, 148, 0.1)' : 'rgba(35, 78, 148, 0.05)',
        gap: 10,
    },
    drawHeroText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.PRIMARY_ACTIVE_BUTTON,
    },
    cardRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        gap: 10,
        paddingHorizontal: 0,
    },
    sideSelector: {
        gap: 8,
        alignItems: 'center',
    },
    bgOptionBtn: {
        width: 26,
        height: 26,
        borderRadius: 14,
        borderWidth: 0.5,
        borderColor: 'transparent',
        padding: 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
    bgOptionActive: {
        borderColor: colors.PRIMARY_TEXT,
    },
    bgOptionInner: {
        width: '100%',
        height: '100%',
        borderRadius: 14,
        borderWidth: 0.5,
        borderColor: 'rgba(0,0,0,0.1)',
    },
    sideNumberSelector: {
        gap: 8,
        alignItems: 'center',
    },
    numberBtn: {
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)',
    },
    numberBtnActive: {
        backgroundColor: colors.PRIMARY_ACTIVE_BUTTON,
        borderColor: colors.PRIMARY_ACTIVE_BUTTON,
    },
    numberBtnText: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.PRIMARY_TEXT,
    },
    numberBtnTextActive: {
        color: '#FFFFFF',
    },
})
