import { StyleSheet } from "react-native";

export const getStyles = (colors: any, isDark: boolean) =>
  StyleSheet.create({
    container: {
      backgroundColor: colors.SECONDARY_BACKGROUND,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: isDark ? colors.PRIMARY_BORDER_DARK : colors.PRIMARY_BORDER,
      padding: 20,
      width: 340,
      maxWidth: "95%",
      alignItems: "center",
      gap: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDark ? 0.3 : 0.2,
      shadowRadius: isDark ? 20 : 15,
      elevation: 10,
    },
    headerRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
      width: "100%",
      marginBottom: 4,
    },
    iconContainer: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.SECONDARY_BACKGROUND,
      shadowColor: colors.CHECKBOX_SUCCESS,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 2,
    },
    headerText: {
      fontSize: 14,
      fontWeight: "bold",
      textAlign: "center",
      opacity: 0.9,
      color: colors.PRIMARY_TEXT,
    },
    divider: {
      height: 0.6,
      backgroundColor: colors.PRIMARY_BORDER_DARK,
      width: "100%",
      opacity: 0.8,
      marginVertical: 4,
    },
    messageText: {
      fontSize: 14,
      color: colors.PLACEHOLDER,
      textAlign: "center",
      lineHeight: 20,
    },
    instructionBox: {
      width: "100%",
      borderRadius: 16,
      padding: 16,
      backgroundColor: isDark
        ? "rgba(255, 255, 255, 0.05)"
        : "rgba(0, 0, 0, 0.03)",
      borderWidth: 1,
      borderColor: isDark ? "rgba(255, 255, 255, 0.1)" : "rgba(0, 0, 0, 0.1)",
      marginVertical: 4,
    },
    instructionText: {
      fontSize: 13,
      fontWeight: "600",
      marginBottom: 8,
      color: colors.PRIMARY_TEXT,
    },
    instructionDetail: {
      fontSize: 12,
      lineHeight: 18,
      color: colors.PLACEHOLDER,
    },
  });
