import { StyleSheet } from "react-native";

export const BIRTHDAY_PRIMARY = "#4F46E5";
export const BIRTHDAY_LIGHT = "#6366F1";
export const BIRTHDAY_BG_LIGHT = "rgba(79, 70, 229, 0.08)";
export const BIRTHDAY_BG_STRONG_LIGHT = "rgba(79, 70, 229, 0.15)";
export const BIRTHDAY_BORDER_LIGHT = "rgba(79, 70, 229, 0.15)";

export const getStyles = (colors: any, isDark: boolean) => StyleSheet.create({
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: 'space-between',
        paddingTop: 15,
        paddingBottom: 10,
        paddingHorizontal: 20,
    },
    headerTitle: {
        fontSize: 24,
        marginBottom: 4,
        fontWeight: "bold",
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingBottom: 100,
    },
    sectionContainer: {
        marginBottom: 0,
    },
    sectionHeaderCard: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        paddingLeft: 10,
        paddingRight: 20,
        paddingVertical: 13,
        borderRadius: 20,
        marginTop: 6,
        marginBottom: 5,
        overflow: 'hidden',
        position: 'relative',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
    },
    sectionTitleContainer: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        width: 175,
        zIndex: 2,
    },
    sectionTitleCard: {
        fontSize: 15,
        fontWeight: "600",
        color: colors.PRIMARY_TEXT,
    },
    cardBadge: {
        backgroundColor: isDark ? 'rgba(255,255,255,0.15)' : 'rgba(0, 0, 0, 0.06)',
        paddingHorizontal: 10,
        paddingVertical: 2,
        borderRadius: 10,
        marginLeft: 4,
    },
    cardBadgeText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: colors.PRIMARY_TEXT,
    },
    decorativeCircle: {
        position: 'absolute',
        width: 80,
        height: 80,
        borderRadius: 40,
        bottom: -20,
        right: -20,
        zIndex: 1,
    },
    iconContainer: {
        width: 30,
        height: 30,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sectionControls: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        zIndex: 2,
    },
    chevronZone: {
        width: 24,
        alignItems: 'flex-end',
        justifyContent: 'center',
    },
    // List Item Styles
    card: {
        flexDirection: "row",
        alignItems: "center",
        padding: 14,
        borderRadius: 14,
        borderWidth: 0.2,
        marginBottom: 10,
        gap: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 2,
    },
    // Grid Item Styles
    gridCard: {
        width: '48.5%',
        borderRadius: 20,
        padding: 15,
        marginBottom: 10,
        borderWidth: 0.2,
        height: 165,
        justifyContent: 'space-between',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        position: 'relative',
        overflow: 'hidden',
    },
    gridCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    gridAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    gridAvatarText: {
        fontSize: 16,
        fontWeight: '700',
    },
    gridCardBody: {
        flex: 1,
        justifyContent: 'center',
        marginTop: 8,
    },
    gridName: {
        fontSize: 15,
        fontWeight: '600',
        marginBottom: 2,
    },
    gridDate: {
        fontSize: 12,
        opacity: 0.8,
    },
    gridCardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 'auto',
        paddingTop: 8,
        borderTopWidth: 0.2,
        borderTopColor: colors.PRIMARY_BORDER_DARK,
    },
    gridMetadata: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        flex: 1,
    },
    gridDaysBadge: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 6,
    },
    gridDaysText: {
        fontSize: 10,
        fontWeight: '600',
    },
    gridContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        paddingVertical: 5,
    },
    avatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: "center",
        alignItems: "center",
    },
    avatarText: {
        fontSize: 20,
        fontWeight: "700",
    },
    cardContent: {
        flex: 1,
        gap: 3,
    },
    nameRow: {
        flexDirection: "row",
        alignItems: "center",
    },
    name: {
        fontSize: 15,
        fontWeight: "600",
    },
    infoRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    dateText: {
        fontSize: 12,
    },
    dot: {
        width: 3,
        height: 3,
        borderRadius: 1.5,
        backgroundColor: "#888",
    },
    daysBadge: {
        alignSelf: "flex-start",
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 6,
        marginTop: 2,
    },
    daysText: {
        fontSize: 11,
        fontWeight: "600",
    },
    notificationStatus: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        marginTop: 2,
    },
    actions: {
        flexDirection: "column",
        gap: 6,
    },
    actionButton: {
        width: 34,
        height: 34,
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    viewToggleButton: {
        width: 38,
        height: 38,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 0.2,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 20,
    },
    emptyIcon: {
        width: 120,
        height: 120,
        borderRadius: 60,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 24,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    emptyButton: {
        paddingVertical: 16,
        paddingHorizontal: 32,
        borderRadius: 15,
        borderWidth: 1,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    stickySectionHeader: {
        marginHorizontal: 16,
        marginTop: 6,
        marginBottom: 2,
    },
});
